import { buildInterviewCitations } from "@/lib/interview-citations";
import { getDemoQuestionTexts } from "@/lib/demo-mode";
import { generateInterviewQuestions } from "@/lib/maizey-client";
import { generateInterviewResponse } from "@/lib/um-gpt-client";
import {
  InterviewChatMessage,
  InterviewChatRequest,
  InterviewChatResponse,
  InterviewChatSessionState,
  InterviewSessionSnapshotResponse,
  InterviewStartRequest,
  InterviewStartResponse,
} from "@/types/legacy-loop";

const MIN_FOLLOW_UPS_PER_QUESTION = 1;
const MAX_FOLLOW_UPS_PER_QUESTION = 2;

class InterviewEngineError extends Error {
  status: number;

  constructor(message: string, status = 400) {
    super(message);
    this.status = status;
  }
}

type GlobalWithInterviewSessions = typeof globalThis & {
  __legacyLoopInterviewSessions?: Map<string, InterviewChatSessionState>;
};

const globalForInterview = globalThis as GlobalWithInterviewSessions;
const sessions =
  globalForInterview.__legacyLoopInterviewSessions ??
  new Map<string, InterviewChatSessionState>();

if (!globalForInterview.__legacyLoopInterviewSessions) {
  globalForInterview.__legacyLoopInterviewSessions = sessions;
}

function makeMessage(
  role: InterviewChatMessage["role"],
  content: string,
  questionId: string,
  questionNumber: number,
  options?: {
    reasoningSummary?: string;
    citations?: InterviewChatMessage["citations"];
  },
): InterviewChatMessage {
  return {
    id: globalThis.crypto.randomUUID(),
    role,
    content,
    createdAt: new Date().toISOString(),
    questionId,
    questionNumber,
    reasoningSummary: options?.reasoningSummary,
    citations: options?.citations,
  };
}

function makeQuestionPrompt(questionText: string, questionNumber: number, total: number): string {
  return `Question ${questionNumber} of ${total}: ${questionText}`;
}

export async function getInterviewSessionSnapshot(
  sessionId: string,
): Promise<InterviewSessionSnapshotResponse> {
  const session = sessions.get(sessionId);
  if (!session) {
    throw new InterviewEngineError("Session not found. Restart interview.", 404);
  }

  const totalQuestions = session.questions.length;
  const boundedQuestionIndex = Math.max(
    0,
    Math.min(session.currentQuestionIndex, Math.max(totalQuestions - 1, 0)),
  );
  const currentQuestion = session.questions[boundedQuestionIndex];
  const currentQuestionNumber = totalQuestions > 0 ? boundedQuestionIndex + 1 : 1;

  return {
    sessionId: session.sessionId,
    messages: session.messages,
    currentQuestionId: currentQuestion?.id,
    currentQuestionNumber,
    completedCount: session.completedQuestionIds.length,
    totalQuestions,
    done: session.done,
  };
}

export async function startInterviewSession(
  input: InterviewStartRequest,
): Promise<InterviewStartResponse> {
  if (!input?.resourceContext) {
    throw new InterviewEngineError("resourceContext is required.", 400);
  }

  const demoModeEnabled = input.demoMode?.enabled === true;
  const questionTexts = demoModeEnabled
    ? getDemoQuestionTexts(input.demoMode?.profile ?? "three-min")
    : await generateInterviewQuestions(input.resourceContext);

  if (questionTexts.length === 0) {
    throw new InterviewEngineError("No interview questions available.", 500);
  }

  const sessionId = globalThis.crypto.randomUUID();
  const questions = questionTexts.map((text, index) => ({
    id: `q-${index + 1}`,
    text,
  }));

  const firstQuestion = questions[0];

  const initialAssistantMessage = makeMessage(
    "assistant",
    makeQuestionPrompt(firstQuestion.text, 1, questions.length),
    firstQuestion.id,
    1,
    {
      reasoningSummary:
        demoModeEnabled
          ? "Demo mode: using scripted fallback interview prompts."
          : "Questions were generated by the Maizey RAG knowledge base using your selected data sources and preloaded leadership documents.",
      citations: buildInterviewCitations(input.resourceContext, firstQuestion.text, ""),
    },
  );

  const session: InterviewChatSessionState = {
    sessionId,
    questions,
    currentQuestionIndex: 0,
    completedQuestionIds: [],
    messages: [initialAssistantMessage],
    resourceContext: input.resourceContext,
    followUpCountByQuestion: {},
    done: false,
    demoMode: input.demoMode,
  };

  sessions.set(sessionId, session);

  return {
    sessionId,
    messages: [initialAssistantMessage],
    currentQuestionId: firstQuestion.id,
    currentQuestionNumber: 1,
    totalQuestions: questions.length,
    done: false,
  };
}

export async function answerInterviewMessage(
  input: InterviewChatRequest,
): Promise<InterviewChatResponse> {
  const session = sessions.get(input.sessionId);
  if (!session) {
    throw new InterviewEngineError("Session not found. Restart interview.", 404);
  }

  const userText = input.message?.trim();
  if (!userText) {
    throw new InterviewEngineError("Message is required.", 400);
  }

  if (session.done) {
    const finalQuestionIndex = Math.max(
      0,
      Math.min(session.currentQuestionIndex, session.questions.length - 1),
    );
    const finalQuestion = session.questions[finalQuestionIndex];
    const finalQuestionId = finalQuestion?.id ?? "q-final";
    const finalQuestionText = finalQuestion?.text ?? "Final interview context";
    const finalQuestionNumber = finalQuestionIndex + 1;
    const userMessage = makeMessage(
      "user",
      userText,
      finalQuestionId,
      finalQuestionNumber,
    );
    const assistantMessage = makeMessage(
      "assistant",
      "Additional context recorded. Click Finish whenever you are ready to end the interview.",
      finalQuestionId,
      finalQuestionNumber,
      {
        reasoningSummary: "Interview was already complete; captured supplemental context.",
        citations: buildInterviewCitations(
          session.resourceContext,
          finalQuestionText,
          userText,
        ),
      },
    );
    session.messages.push(userMessage, assistantMessage);

    return {
      messages: [userMessage, assistantMessage],
      completedCount: session.completedQuestionIds.length,
      totalQuestions: session.questions.length,
      done: true,
    };
  }

  const currentQuestion = session.questions[session.currentQuestionIndex];
  if (!currentQuestion) {
    session.done = true;
    return {
      messages: [],
      completedCount: session.completedQuestionIds.length,
      totalQuestions: session.questions.length,
      done: true,
    };
  }

  const questionNumber = session.currentQuestionIndex + 1;
  const userMessage = makeMessage("user", userText, currentQuestion.id, questionNumber);
  session.messages.push(userMessage);

  const followUpCount = session.followUpCountByQuestion[currentQuestion.id] ?? 0;

  if (session.demoMode?.enabled) {
    if (!session.completedQuestionIds.includes(currentQuestion.id)) {
      session.completedQuestionIds.push(currentQuestion.id);
    }

    const nextQuestionIndex = session.currentQuestionIndex + 1;
    const hasMoreQuestions = nextQuestionIndex < session.questions.length;

    if (!hasMoreQuestions) {
      session.done = true;
      const assistantMessage = makeMessage(
        "assistant",
        "Thanks. That completes the scripted demo interview and the handoff capsule is ready.",
        currentQuestion.id,
        questionNumber,
        {
          reasoningSummary: "Demo mode completed scripted interview sequence.",
          citations: buildInterviewCitations(
            session.resourceContext,
            currentQuestion.text,
            userText,
          ),
        },
      );
      session.messages.push(assistantMessage);

      return {
        messages: [userMessage, assistantMessage],
        completedCount: session.completedQuestionIds.length,
        totalQuestions: session.questions.length,
        done: true,
      };
    }

    session.currentQuestionIndex = nextQuestionIndex;
    const nextQuestion = session.questions[nextQuestionIndex];
    const assistantMessage = makeMessage(
      "assistant",
      makeQuestionPrompt(nextQuestion.text, nextQuestionIndex + 1, session.questions.length),
      nextQuestion.id,
      nextQuestionIndex + 1,
      {
        reasoningSummary: "Demo mode advanced to the next scripted interview question.",
        citations: buildInterviewCitations(
          session.resourceContext,
          nextQuestion.text,
          userText,
        ),
      },
    );
    session.messages.push(assistantMessage);

    return {
      messages: [userMessage, assistantMessage],
      currentQuestionId: nextQuestion.id,
      currentQuestionNumber: nextQuestionIndex + 1,
      completedCount: session.completedQuestionIds.length,
      totalQuestions: session.questions.length,
      done: false,
    };
  }

  // Force advance after MAX_FOLLOW_UPS regardless of GPT decision
  const forceAdvance = followUpCount >= MAX_FOLLOW_UPS_PER_QUESTION;

  // Call U-M GPT Toolkit for real-time response generation
  const turn = await generateInterviewResponse(
    session.messages,
    currentQuestion.text,
    questionNumber,
    session.questions.length,
    session.resourceContext,
  );

  const shouldAdvance = forceAdvance || (followUpCount >= MIN_FOLLOW_UPS_PER_QUESTION && turn.advance);

  if (!shouldAdvance) {
    session.followUpCountByQuestion[currentQuestion.id] = followUpCount + 1;

    const assistantMessage = makeMessage(
      "assistant",
      turn.message,
      currentQuestion.id,
      questionNumber,
      {
        reasoningSummary: turn.reasoning,
        citations: buildInterviewCitations(
          session.resourceContext,
          currentQuestion.text,
          userText,
        ),
      },
    );
    session.messages.push(assistantMessage);

    return {
      messages: [userMessage, assistantMessage],
      currentQuestionId: currentQuestion.id,
      currentQuestionNumber: questionNumber,
      completedCount: session.completedQuestionIds.length,
      totalQuestions: session.questions.length,
      done: false,
    };
  }

  // Advance to next question
  if (!session.completedQuestionIds.includes(currentQuestion.id)) {
    session.completedQuestionIds.push(currentQuestion.id);
  }

  const nextQuestionIndex = session.currentQuestionIndex + 1;
  const hasMoreQuestions = nextQuestionIndex < session.questions.length;

  if (!hasMoreQuestions) {
    session.done = true;
    const assistantMessage = makeMessage(
      "assistant",
      turn.message ||
        "Thanks for the detailed responses. This completes the interview, and your knowledge capsule is now ready for handoff.",
      currentQuestion.id,
      questionNumber,
      {
        reasoningSummary: turn.reasoning || "All core interview topics have enough detail for transfer readiness.",
        citations: buildInterviewCitations(
          session.resourceContext,
          currentQuestion.text,
          userText,
        ),
      },
    );
    session.messages.push(assistantMessage);

    return {
      messages: [userMessage, assistantMessage],
      completedCount: session.completedQuestionIds.length,
      totalQuestions: session.questions.length,
      done: true,
    };
  }

  session.currentQuestionIndex = nextQuestionIndex;
  const nextQuestion = session.questions[nextQuestionIndex];

  const transitionMessage = `${turn.message ? `${turn.message} ` : "Thanks, that level of detail is helpful. "}${makeQuestionPrompt(nextQuestion.text, nextQuestionIndex + 1, session.questions.length)}`;

  const assistantMessage = makeMessage(
    "assistant",
    transitionMessage,
    nextQuestion.id,
    nextQuestionIndex + 1,
    {
      reasoningSummary:
        turn.reasoning || "Sufficient detail captured for this topic, moving to the next area.",
      citations: buildInterviewCitations(
        session.resourceContext,
        nextQuestion.text,
        userText,
      ),
    },
  );
  session.messages.push(assistantMessage);

  return {
    messages: [userMessage, assistantMessage],
    currentQuestionId: nextQuestion.id,
    currentQuestionNumber: nextQuestionIndex + 1,
    completedCount: session.completedQuestionIds.length,
    totalQuestions: session.questions.length,
    done: false,
  };
}

export { InterviewEngineError };
